Additional information for the globemallow extension
Adora-Foundation/awesome-green-extensions pull request #5
Opened 2022-10-04 08:28 UTC by mandyh101

I have filled in the missing info for the Globemallow extension! Let me know if you think there is anything missing or to be improved! Thank you :)

2022-10-05 21:07 UTC, Leamsi9 requested changes
This is excellent @mandyh101 ! Better than I had designed it, really like the extra data you've added. Only a minor styling header hierarchy. Since the title on line 1 is an H1 (#) the remaining headers need to cascade accordingly, so need to add a hash to all the others. When that's done, we can merge it away! Thanks a lot!

2022-10-05 21:07 UTC, Leamsi9 commented on README.md
> +# CO2 emissions trackers and green website raters
This should be an H2 (##) because we are using H1(#) for the main title on line 1

2022-10-05 21:07 UTC, Leamsi9 commented on README.md
> +## Globemallow
This should be an h3

2022-10-05 21:07 UTC, Leamsi9 commented on README.md
> +### Description
And an h4 here (####)

2022-10-06 07:33 UTC, mandyh101 commented
Thanks @Leamsi9 I have updated the headings in the markdown - it looks much better now! I pushed these changes to my main branch so I believe the PR should be updated now too :)

2022-10-06 23:09 UTC, merged